### ISSUE TITLE
Can't create ingress in rancher after importing cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3s#428]
**To Reproduce**
1.  Create k3s server with 2 agents (I used aws)
2.  Import into Rancher 2
3.  Using Rancher create a workload with 2 pods and image nginx
4.  Using Rancher Add Ingress, auto generate .xip.io hostname, Target nginx workload & port 80.

**Results**  LB never finishes initializing.  Error & Warnings in traefik pod, "Endpoint not found for default/ingress"

**Screenshots**
![image](https://user-images.githubusercontent.com/11514927/57051020-308a9b00-6c34-11e9-8410-735e9c114ee5.png)

**Comment by erikwilson** [comment]
Hopefully fixed with #534

**Comment by galal-hussein** [comment]
k3s version: v0.7.0-rc6

I wasn't able to reproduce the issue, however I can still see the problem with creating an ingress, the ingress is created but doesn't proxy any requests to the pods.

**Comment by davidnuzik** [comment]
@galal-hussein when you have spare time could you look again in latest rc? Based on discussion today we _think_ this is fixed (the issue you mentioned in your comment). Not a high priority but I think we should ideally get this working for GA. Curious if fixed.

**Comment by galal-hussein** [comment]
@davidnuzik I am still reproducing the issue when importing k3s aws server with 2 aws agents, the xip.io address translates to the server's internal address:
```
root@ip-172-31-41-58:~# dig nginxlb.default.172.31.37.30.xip.io

; <<>> DiG 9.10.3-P4-Ubuntu <<>> nginxlb.default.172.31.37.30.xip.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17447
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nginxlb.default.172.31.37.30.xip.io. IN	A

;; ANSWER SECTION:
nginxlb.default.172.31.37.30.xip.io. 60	IN A	172.31.37.30
```

**Comment by davidnuzik** [comment]
The PR introduces a new flag and so there is a documentation impact. Created https://github.com/rancher/k3s/issues/905 to address this (needs to at least be in FAQ or possibly anywhere that mentions cloud-provider.

**Comment by davidnuzik** [comment]
External IP was tested and should be working in v0.10.0 release. We will work to validate this specific issue however post-release.

**Comment by davidnuzik** [comment]
Back to-test; should ensure is working correctly in Rancher when leverage the external ip (cloud feature).

**Comment by ShylajaDevadiga** [comment]
Resolved. Verified with k3s v0.11.0-alpha4 passing the --node-external-ip flag. Closing issue. 
@tfiduccia please feel free to re-open if you still see issues creating ingress.
